version: "3"
services:
  server:
    image: "air"
    volumes:
      - ../:/app
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /app/test
    environment:
      - GOPROXY=https://goproxy.cn,direct
    networks:
      - app
    entrypoint:
      - /entrypoint.sh
    ports:
      - 80:8080
  mysql:
    image: "mysql:8.2"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=main
    networks:
      - app
  redis:
    image: "redis:7.2"
    ports:
     - "6379:6379"
    networks:
      - app
networks:
  app: