CREATE TABLE users (
    `id` BIGINT UNSIGNED PRIMARY KEY,
    `username` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户名',
    `password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
    `created_at` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `updated_at` BIGINT UNSIGNED NOT NULL DEFAULT 0
) COMMENT='用户表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;